version: '3.7'
networks:
  default: 
    name: jenkins
services:
  jenkins:
    image: jenkins/jenkins:lts-jdk11
    restart: always
    user: '0'
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.ssh:/root/.ssh
      - ${DOCKER_PATH}:/usr/bin/docker
  nginx:
    build: nginx
    container_name: nginx
    restart: always
    environment:
      TZ: ${TIMEZONE:-Europe/Kiev}
      MODE: ${NGINX_MODE:-default}
    volumes:
      - ${PWD}/system/certbot/conf:/etc/letsencrypt
      - ${PWD}/system/certbot/www:/var/www/certbot
    ports:
      - 80:80
      - 443:443
  mailserver:
    image: docker.io/mailserver/docker-mailserver:latest
    container_name: mailserver
    hostname: mail-server
    # example.com should be replaced with the own domain for the mail server:
    domain name: hisokajenkins.space
    ports:
      - 25:25
      - 587:587
      - 465:465
    volumes:
      - ./docker-data/dms/mail-data/:/var/mail/
      - ./docker-data/dms/mail-state/:/var/mail-state/
      - ./docker-data/dms/mail-logs/:/var/log/mail/
      - ./docker-data/dms/config/:/tmp/docker-mailserver/
      # Path should be adjusted accordingly:
      - ./docker-data/nginx-proxy/certs/:/etc/letsencrypt/
      - /etc/localtime:/etc/localtime:ro
    environment:
      - ENABLE_FAIL2BAN=1
      # If letsencrypt for SSL/TLS certificate is used (otherwise adapt)
      - SSL_TYPE=letsencrypt
      - PERMIT_DOCKER=network
      - ONE_DIR=1
      - ENABLE_POSTGREY=0
      - ENABLE_CLAMAV=0
      - ENABLE_SPAMASSASSIN=0
      - SPOOF_PROTECTION=0
    cap_add:
      - NET_ADMIN # For Fail2Ban to work
      - SYS_PTRACE
  certbot:
    image: certbot/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    container_name: certbot
    volumes:
      - ${PWD}/system/certbot/conf:/etc/letsencrypt
      - ${PWD}/system/certbot/www:/var/www/certbot
    

